<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Refresh" content="10; url=index.php">
    <title>We Value your Feedback</title>
    <link rel="stylesheet" href="css/foundation.css">
</head>
<body>
<div>
<h3>Thank You for your valuable feedback. Your questions and concerns will be evaluated, and we will get back to you within the next 50 years.</h3></div>
<p>
<h3>You will be redirected to the Home Page.</h3>
</p>
<p>Or, you can click <a href="index.php">here</a> to go back now.</p>
</body>
</html>